#!/usr/bin/env bash
# This file is part of the Agave project 
# https://github.com/dmedri/agave/
# Copyright (c) 2019-2020 Daniele Medri.
# 
# This program is free software: you can redistribute it and/or modify  
# it under the terms of the GNU General Public License as published by  
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <http://www.gnu.org/licenses/>.                                


# Libraries
source lib/libagave.sh

# Header
agave-header

# Commands: evaluate status
check-cmdreq {R,git}

# Help menu
while [[ -n "$1" ]]; do
	case $1 in
	"-b")
		r-build $2
		;;
	"-bc")
		r-build $2
		r-check $2
		;;
	"-bi")
		r-build $2
		r-install $2
		;;
	"-c")
		r-check $2
		;;
	"-cc")
		r-check-cran $2
		;;
	"-i")
		r-install $2
		;;
	"-r")
		r-remove $2
		;;
	"--help")
		app-options
		;;
	esac
	shift
done
